# Generated by Django 3.2.18 on 2023-03-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='salary',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=40),
        ),
    ]
